# Generated by Django 4.2 on 2025-12-23 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firearms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firearms_name', models.CharField(max_length=100)),
                ('firearms_image', models.CharField(default=None, max_length=200)),
                ('firearms_price', models.IntegerField()),
                ('firearms_description', models.TextField(max_length=500)),
                ('firearms_ammo', models.TextField(max_length=100)),
                ('firearms_ammo_capacity', models.TextField(max_length=100)),
                ('firearms_caliber', models.TextField(max_length=100)),
                ('firearms_barrel_length', models.TextField(max_length=100)),
                ('firearms_overall_length', models.CharField(max_length=100)),
                ('firearms_weight', models.CharField(max_length=100)),
                ('firearms_finish', models.CharField(max_length=100)),
                ('firearms_action', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
