# Generated by Django 4.2 on 2025-12-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearms',
            name='firearms_action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_ammo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_ammo_capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_barrel_length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_caliber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_finish',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_overall_length',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firearms',
            name='firearms_weight',
            field=models.CharField(max_length=50),
        ),
    ]
