# Generated by Django 4.2 on 2025-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0002_alter_firearms_firearms_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearms',
            name='firearms_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
