# Generated by Django 4.2 on 2025-12-21 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=20, null=True)),
                ('client_subject', models.CharField(max_length=100)),
                ('client_message', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
