# Generated by Django 4.2 on 2025-12-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=20, null=True)),
                ('user_password', models.CharField(max_length=25)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
