# Generated by Django 4.2 on 2025-12-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='client_phone_number',
            new_name='user_phone_number',
        ),
    ]
