# Generated by Django 4.2 on 2025-12-27 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_first_name', models.CharField(max_length=100)),
                ('buyer_last_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=100)),
                ('buyer_phone_number', models.CharField(max_length=20, null=True)),
                ('buyer_dealer_name', models.CharField(max_length=100)),
                ('buyer_street_address', models.CharField(default=None, max_length=200)),
                ('buyer_city', models.CharField(default=None, max_length=50)),
                ('buyer_state', models.CharField(default=None, max_length=50)),
                ('buyer_zip_code', models.CharField(default=None, max_length=10)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('buyer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.users')),
            ],
        ),
    ]
