# Generated by Django 4.2 on 2025-12-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='buyer_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
