# Generated by Django 4.2 on 2026-01-04 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_orders_buyer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
