# Generated by Django 4.2 on 2026-01-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_users_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='added_date',
        ),
    ]
