# Generated by Django 4.2 on 2026-01-04 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_users_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
